module AocCli
  module Components
    class DocsComponent < Kangaru::Component
      include Helpers::ViewHelper

      ENDPOINTS: Hash[Symbol, untyped]

      def endpoints: -> Hash[Symbol, untyped]

      def title: -> String

      def commands_table: (Hash[Symbol, String], ?indent: Integer) -> String
    end
  end
end
