module AocCli
  module Presenters
    class PuzzlePresenter
      attr_reader puzzle: Puzzle

      def initialize: (Puzzle) -> void

      def date: -> String

      def puzzle_filename: -> String

      def input_filename: -> String

      private

      def formatted_day: -> String
    end
  end
end
