module AocCli
  module Helpers
    module ViewHelper
      def main_header: -> String

      def heading: (String) -> String

      def success_tag: -> String

      def table_for: (*Array[String], ?gap: Integer, ?indent: Integer) -> String

      def wrap_text: (String, ?width: Integer, ?indent: Integer) -> String
    end
  end
end
