module AocCli
  class Event < Kangaru::Model
    attr_accessor id: Integer
    attr_accessor year: Integer
    attr_accessor created_at: Time
    attr_accessor updated_at: Time

    attr_accessor puzzles: Array[Puzzle]
    attr_accessor stats: Stats
  end
end
