module AocCli
  class Progress < Kangaru::Model
    attr_accessor id: Integer
    attr_accessor puzzle: Puzzle
    attr_accessor level: Integer
    attr_accessor started_at: Time
    attr_accessor completed_at: Time
    attr_accessor created_at: Time
    attr_accessor updated_at: Time

    def complete?: -> bool

    def incomplete?: -> bool

    def complete!: -> void

    def reset!: -> void

    def time_taken: -> Float
  end
end
