module AocCli
  class Puzzle < Kangaru::Model
    extend Forwardable

    attr_accessor id: Integer
    attr_accessor event: Event
    attr_accessor day: Integer
    attr_accessor content: String
    attr_accessor input: String
    attr_accessor created_at: Time
    attr_accessor updated_at: Time
    attr_accessor part_one_completed_at: Time
    attr_accessor part_two_completed_at: Time

    attr_accessor location: Location
    attr_accessor location_dataset: Sequel::Dataset

    attr_accessor attempts: Array[Attempt]
    attr_accessor attempts_dataset: Sequel::Dataset

    attr_accessor part_one_progress: Progress?
    attr_accessor part_two_progress: Progress?

    # Delegated to event
    def year: -> Integer

    attr_reader presenter: Presenters::PuzzlePresenter
  end
end
