module AocCli
  class Puzzle < Kangaru::Model
    attr_accessor id: Integer
    attr_accessor event: Event
    attr_accessor day: Integer
    attr_accessor content: String
    attr_accessor input: String
    attr_accessor created_at: Time
    attr_accessor updated_at: Time
    attr_accessor part_one_completed_at: Time
    attr_accessor part_two_completed_at: Time

    attr_accessor location: Location
    attr_accessor attempts: Array[Attempt]

    def mark_complete!: (Integer) -> void
  end
end
