module AocCli
  module Core
    class Repository
      HOST: String

      RESOURCES: Hash[Symbol, Hash[Symbol, String]]

      def self.get_puzzle: (year: Integer, day: Integer) -> String

      private

      def self.build_resource: (Symbol, **untyped) -> Resource

      def self.format_url: (String, **untyped) -> String
    end
  end
end
