module AocCli
  module Core
    class Repository
      HOST: String

      RESOURCES: Hash[Symbol, Hash[Symbol, untyped]]

      def self.get_stats: (year: Integer) -> Hash[Symbol, Integer]

      def self.get_puzzle: (year: Integer, day: Integer) -> String

      def self.get_input: (year: Integer, day: Integer) -> String

      def self.post_solution: (
        year: Integer, day: Integer, level: Integer, answer: untyped
      ) -> Hash[Symbol, untyped]

      private

      def self.build_resource: (Symbol, **untyped) -> Resource

      def self.format_url: (String, **untyped) -> String
    end
  end
end
