module AocCli
  module Core
    class Request
      extend Forwardable

      attr_reader client: HTTP::Client

      def initialize: (token: String) -> void

      def get: (String) -> HTTP::Response

      def self.build: -> Request

      def self.get: (String) -> HTTP::Response

      class ::Class
        def def_delegators: (Symbol, *Symbol) -> void
      end

      private

      def setup_client!: (String) -> HTTP::Client
    end
  end
end
