module AocCli
  module Core
    class Request
      attr_reader client: HTTP::Client

      def initialize: (token: String) -> void

      def self.build: -> Request

      private

      def setup_client!: (String) -> HTTP::Client
    end
  end
end
