module AocCli
  module Core
    class Request
      extend Forwardable

      attr_reader client: HTTP::Client
      attr_reader ssl_context: OpenSSL::SSL::SSLContext

      def initialize: (token: String) -> void

      def get: (String) -> HTTP::Response

      def post: (String, **untyped) -> HTTP::Response

      def self.build: -> Request

      def self.get: (String) -> HTTP::Response

      def self.post: (String, **untyped) -> HTTP::Response

      class ::Class
        def def_delegators: (Symbol, *Symbol) -> void
      end

      private

      def setup_client!: (String) -> HTTP::Client

      def setup_ssl_context!: -> OpenSSL::SSL::SSLContext

      def default_options: -> Hash[Symbol, untyped]
    end
  end
end
