module AocCli
  module Core
    class Resource
      attr_reader url: String
      attr_reader scope: String?
      attr_reader method: Symbol
      attr_reader params: Hash[Symbol, untyped]

      def initialize: (
        url: String,
        ?scope: String?,
        ?method: Symbol,
        ?params: Hash[Symbol, untyped]
      ) -> void

      def fetch: -> String

      def fetch_markdown: -> String

      private

      def response: -> String
    end
  end
end
