module AocCli
  class ApplicationController < Kangaru::Controller
    include Concerns::ErrorConcern
    include Concerns::LocationConcern

    include Helpers::ViewHelper

    private

    def handle_help_param!: -> void
  end
end
