module AocCli
  class EventController < ApplicationController
    @event: Event

    def init: -> void

    @source: String
    @target: String

    def attach: -> void

    def progress: -> void

    private

    attr_reader queried_event: Event?
  end
end
