module AocCli
  class PuzzleController < ApplicationController
    @puzzle: Puzzle
    @attempt: Attempt
    @sync_log: PuzzleDirSyncLog

    def init: -> void

    def solve: -> void

    def sync: -> void

    def attempts: -> void
  end
end
