module AocCli
  class PuzzleController < ApplicationController
    @puzzle: Puzzle
    @attempt: Attempt?

    def init: -> void

    def solve: -> void

    def sync: -> void

    def attempts: -> void

    private

    def validate_in_event_dir!: -> void

    def validate_in_puzzle_dir!: -> void
  end
end
