module AocCli
  module Processors
    class EventInitialiser < Core::Processor
      attr_accessor year: Integer
      attr_accessor dir: String

      def self.run!: (year: untyped, dir: untyped) -> Event

      private

      attr_reader event_dir: Pathname

      def create_event!: -> Event

      def initialise_stats!: (Event) -> void

      def make_event_directory!: -> void

      def attach_event!: (Event) -> void

      def validate_event_dir_does_not_exist!: -> void

      def validate_event_not_already_initialised!: -> void
    end
  end
end
