module AocCli
  module Processors
    class PuzzleRefresher < Core::Processor
      attr_accessor year: Integer
      attr_accessor day: Integer
      attr_accessor use_cache: bool

      def run: -> Puzzle?

      private

      attr_reader event: Event?
      attr_reader puzzle: Puzzle?

      def fetch_content!: -> String

      def fetch_input!: -> String

      def create_or_update_puzzle!: (String, String) -> Puzzle

      def validate_event_set!: -> void
    end
  end
end
