module AocCli
  module Processors
    class SolutionPoster < Core::Processor
      attr_accessor year: Integer
      attr_accessor day: Integer
      attr_accessor answer: untyped

      def run: -> Attempt?

      private

      attr_reader event: Event?
      attr_reader puzzle: Puzzle?
      attr_reader stats: Stats
      attr_reader level: Integer

      def puzzle!: -> Puzzle

      def post_solution!: -> Hash[Symbol, untyped]

      def create_attempt!: (Hash[Symbol, untyped]) -> Attempt

      def handle_correct_attempt!: -> void

      def validate_event_exists!: -> void

      def validate_stats_exist!: -> void

      def validate_puzzle_exists!: -> void

      def validate_puzzle_not_complete!: -> void
    end
  end
end
