module AocCli
  module Processors
    class YearInitialiser < Core::Processor
      attr_accessor year: Integer
      attr_accessor dir: String

      private

      attr_reader year_dir: String

      def find_or_create_event!: -> Event

      def fetch_stats!: -> void

      def create_or_update_location!: (Event) -> void

      def make_year_directory!: -> void

      def validate_year_dir_does_not_exist!: -> void
    end
  end
end
